### PR TITLE
remove broken require statement

### PR DESCRIPTION
**Pull request by rmoriz**
fixes:

```
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/deploy_resource/libraries/provider_revision.rb
================================================================================

LoadError
---------
cannot load such file -- chef/provider/deploy

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/deploy_resource/libraries/provider_revision.rb:23:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/deploy_resource/libraries/provider_revision.rb:

 16:  # distributed under the License is distributed on an "AS IS" BASIS,
 17:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 18:  # See the License for the specific language governing permissions and
 19:  # limitations under the License.
 20:  #
 21:  
 22:  require "chef/provider"
 23>> require "chef/provider/deploy"
 24:  require "chef/json_compat"
 25:  
 26:  class Chef
 27:    class Provider
 28:      class Deploy
 29:        class Revision < Chef::Provider::Deploy
 30:          provides :deploy_revision
 31:          provides :deploy_branch
 32:  

System Info:
------------
chef_version=14.0.190
platform=debian
platform_version=8.10
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client


Running handlers:
[2018-04-06T10:22:04+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-04-06T10:22:04+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 05 seconds
[2018-04-06T10:22:04+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-04-06T10:22:04+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-04-06T10:22:04+00:00] FATAL: LoadError: cannot load such file -- chef/provider/deploy

```

Please enable issues for this repo, too. Thanks

### CODE REVIEW

**Comment by rmoriz** [comment]
Travis is not configured and there are no tests in this repo. Can we get the old chef-core unit tests for the resources?

Also I guess you will remove https://docs.chef.io/resource_deploy.html soon, can we save this information in a README in this repo?

**Review by tas50 — APPROVED** [review]

**Comment by tas50** [comment]
We can probably get those old tests copied over. They might need some tweaks to work in a cookbook, but that can probably get done.

**Comment by rmoriz** [comment]
and please enable Github issues…

**Comment by rmoriz** [comment]
@tas50 Ping? Can you please enable github issues?

**Comment by thommay** [comment]
Done

**Pull request merged**
